#SPDX-License-Identifier: MIT-0
---
# tasks file for influxdb
- name: Set project base name
  ansible.builtin.set_fact:
    project_base_name: influxdb

- name: Set Project variables
  ansible.builtin.set_fact:
    project_name: "{{ project_base_name }}{{ project_suffix | default('') }}"

- name: Set Project variables
  ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/podman/{{ project_name }}"

- name: Create directory
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    mode: "0755"

- name: Podman service deployment
  ansible.builtin.include_role:
    name: podman_service_deploy
  vars:
    podman_service_deploy_config:
      networks:
        - name: "{{ project_name }}_default"
          internal: false
        - name: "{{ backend_network }}"
          internal: true
      secrets:
        - name: influx_init_password
          value: "{{ influx_init_password }}"
        - name: influx_init_user
          value: "{{ influx_init_user }}"
      volumes:
        - "{{ project_name }}-influx-data"
        - "{{ project_name }}-influx-config"
      kube_files:
        - "{{ lookup('ansible.builtin.template', 'influx.kube.j2') }}"
