---
# tasks file for maxxberg.onlyoffice-ds
- name: Create project directotory
  file:
    path: docker-compose/onlyoffice
    state: directory

- name: Create docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: docker-compose/onlyoffice/docker-compose.yaml
    force: yes

- name: Docker - Onlyoffice-DS
  docker_compose:
    project_src: docker-compose/onlyoffice/
    state: "{{ state }}"
    pull: yes