FROM docker.io/library/python:3.11-bullseye


#RUN apt update && apt install -y python3 python3-pip python3-venv
RUN apt update && apt install -y git openjdk-11-jre-headless build-essential nano

RUN useradd --create-home user
WORKDIR /home/user
USER user
ENV PATH="/home/user/.local/bin:$PATH"
RUN python3 -m pip install -U pip setuptools wheel &&\
	python3 -m pip install -U Red-DiscordBot
RUN redbot-setup --instance-name redbot --data-path /home/user/redbot --backend json

VOLUME ["/home/user/redbot"]
CMD ["bash", "-c", "redbot redbot --token $REDBOT_TOKEN --prefix $REDBOT_PREFIX"]