# SPDX-License-Identifier: MIT-0
---
# tasks file for bookstack
- name: Set project base name
  ansible.builtin.set_fact:
    project_base_name: bookstack

- name: Set Project variables
  ansible.builtin.set_fact:
    project_name: "{{ project_base_name }}{{ project_suffix | default('') }}"

- name: Set Project variables
  ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/podman/{{ project_name }}"

- name: Set database service name
  ansible.builtin.set_fact:
    db_name: "{{ project_name }}_db"

- name: Set database hostname
  ansible.builtin.set_fact:
    db_hostname: "{{ db_name }}-pod"

- name: Set domain
  ansible.builtin.set_fact:
    domain: "{{ bookstack_domain }}"

- name: Workaround for lazy evaluation
  ansible.builtin.set_fact:
    podman_service_deploy_config:
      networks:
        - name: "{{ project_name }}_default"
          internal: false
        - name: "{{ project_name }}_db"
          internal: true
        - name: "{{ backend_network }}"
          internal: true
      volumes:
        - "{{ project_name }}-www"
      secrets_dict: "{{ bookstack_config.secrets }}"
      kube_files:
        - "{{ lookup('ansible.builtin.template', 'bookstack.kube.j2') }}"
        - "{{ lookup('ansible.builtin.template', 'bookstack-env.configmap.j2') }}"
      mariadb:
        networks:
          - name: "{{ project_name }}_db"
            internal: true
        name: "{{ db_name }}"
        dbname: "{{ project_name }}"
        user: "{{ bookstack_config.db_user | mandatory }}"
        password: "{{ bookstack_config.secrets.DB_PASSWORD | mandatory }}"
        root_password: "{{ bookstack_config.secrets.db_root_password | mandatory }}"
        image_tag: "{{ bookstack_config.mariadb_image_tag | mandatory }}"

- name: Podman service deployment
  ansible.builtin.include_role:
    name: podman_service_deploy
