
---
# tasks file for maxxberg.teamspeak
- name: Docker - Create volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - teamspeak_db_data

#- name: Create docker networks - db_net
#  docker_network:
#    name: db_backend
#    internal: yes
#    state: present

- name: Create docker networks - web_backend
  docker_network:
    name: web_backend
    internal: yes
    state: present

#- name: Upload files
#  copy:
#    src: cloud
#    dest: docker-compose/
- name: Create project directotory
  file:
    path: docker-compose/teamspeak
    state: directory

- name: Create docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: docker-compose/teamspeak/docker-compose.yaml
    force: yes

#- name: Create nextcloud.env
#  template:
#    src: nextcloud.env.j2
#    dest: docker-compose/cloud/nextcloud.env
#    force: yes#

#- name: Create mariadb.env
#  template:
#    src: mariadb.env.j2
#    dest: docker-compose/cloud/mariadb.env
#    force: yes

- name: Docker - teamspeak
  docker_compose:
    project_src: docker-compose/teamspeak/
    state: present
    pull: yes