---
# tasks file for maxxberg.traefik

- name: Set project directory
  ansible.builtin.set_fact:
    project_directory: docker-compose/traefik

- name: Create docker networks - web_backend
  community.docker.docker_network:
    name: "{{ backend_network }}"
    internal: true
    state: present
  when: container_engine == "docker"

- name: Create docker networks - web_backend
  containers.podman.podman_network:
    name: "{{ backend_network }}"
    internal: true
    state: present
  when: container_engine == "podman"

- name: Create project directotory
  ansible.builtin.file:
    path: docker-compose/traefik
    state: directory
    mode: "0755"

- name: Create acme.json
  ansible.builtin.file:
    path: "{{ project_directory }}/acme.json"
    state: file
    mode: "0600"

- name: upload config file
  ansible.builtin.template:
    src: traefik.yaml.j2
    dest: "{{ project_directory }}/traefik.yaml"

- name: Create docker-compose.yaml
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ project_directory }}/docker-compose.yaml"
    force: true

- name: Docker - Traefik
  community.docker.docker_compose:
    project_src: "{{ project_directory }}"
    state: present
    pull: true
