---
# tasks file for maxxberg.zabbix
- name: Docker - Create volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - zabbix_db
    - zabbix_enc
    - zabbix_ssh_keys
    - zabbix_ssl_certs
    - zabbix_ssl_keys
    - zabbix_ssl_sslca

- name: Create docker networks - web_backend
  docker_network:
    name: web_backend
    internal: yes
    state: present

- name: Create project directotory
  file:
    path: docker-compose/zabbix
    state: directory

- name: Create docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: docker-compose/zabbix/docker-compose.yaml
    force: yes

- name: Docker - zabbix
  docker_compose:
    project_src: docker-compose/zabbix/
    state: present
    pull: yes