# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12

recorder:
  db_url: mariadb://homeassistant:mkZCDicvJPw4tRKzys5cbSYkMQLFfW@{{ ha_net_network | ansible.utils.ipmath(7) }}/ha?charset=utf8mb4

influxdb:
  api_version: 2
  host: {{ ha_net_network | ansible.utils.ipmath(5) }}
  port: 8086
  ssl: false
  token: {{ influx_token | default('dummy')}}
  organization: {{ influx_org | default('dummy') }}
  bucket: homeassistant
