---
apiVersion: v1
kind: Deployment
metadata:
  annotations:
    io.containers.autoupdate: registry
  name: {{ project_name }}-db
  labels:
    app: {{ project_name }}
spec:
  selector:
    matchLabels:
      app: {{ project_name }}
  template:
    metadata:
      labels:
        app: {{ project_name }}
      name: {{ project_name }}
    spec:
      containers:
        - name: db
          image: "docker.io/mariadb:{{ homeassistant_db_image_tag | mandatory }}"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db_data
          env:
            - name: MYSQL_HOST
              value: {{ project_name }}-db-pod
            - name: MYSQL_DATABASE
              value: {{ db_name }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: {{ project_name }}_secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: {{ project_name }}_secrets
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_root_password
                  name: {{ project_name }}_secrets
      volumes:
        - name: db_data
          persistentVolumeClaim:
            claimName: {{ project_name }}-db-data
