---
apiVersion: v1
kind: Deployment
metadata:
  annotations:
    io.containers.autoupdate: registry
  name: {{ project_name }}
  labels:
    app: {{ project_name }}
spec:
  selector:
    matchLabels:
      app: {{ project_name }}
  template:
    metadata:
      labels:
        app: {{ project_name }}
        traefik.enable: true
        traefik.http.services.homeassistant-sec.loadbalancer.server.port: 8123
        traefik.http.routers.homeassistant-sec.rule: Host(`{{ homeassistant_domain | mandatory }}`)
        traefik.docker.network: web_backend
        traefik.http.routers.homeassistant-sec.tls: true
        traefik.http.routers.homeassistant-sec.tls.certResolver: letsdns
        traefik.http.routers.homeassistant-sec.middlewares: security_headers@file
        traefik.http.routers.homeassistant.rule: Host(`{{ homeassistant_domain }}`)
        traefik.http.routers.homeassistant.middlewares: redirect-to-https@file
      name: {{ project_name }}
    spec:
      hostNetwork: true
      containers:
        - name: homeassistant
          image: "ghcr.io/home-assistant/home-assistant:stable"
          volumeMounts:
            - mountPath: /config
              name: ha-config
          ports:
            - containerPort: 5683
              hostPort: 5683
              protocol: udp
            - containerPort: 5683
              hostPort: 5683
              protocol: tcp
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: {{ project_name }}-ha-config
