---
# tasks for role homeassistant
- name: Set project base name
  ansible.builtin.set_fact:
    project_base_name: homeassistant

- name: Set Project variables
  ansible.builtin.set_fact:
    project_name: "{{ project_base_name }}{{ project_suffix | default('') }}"

- name: Set Project variables
  ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/podman/{{ project_name }}"

- name: Set database service name
  ansible.builtin.set_fact:
    db_name: "{{ project_name }}_db"

- name: Set database hostname
  ansible.builtin.set_fact:
    db_hostname: "{{ db_name }}-pod"

- name: Workaround for lazy evaluation
  ansible.builtin.set_fact:
    podman_service_deploy_config:
      networks:
        - name: "{{ project_name }}_default"
          internal: false
        - name: "{{ backend_network }}"
          internal: true
        - name: "{{ project_name }}_db"
          internal: true
      secrets: []
      volumes:
        - "{{ project_name }}-ha-config"
        - "{{ project_name }}-db-data"
      kube_files:
        - "{{ lookup('ansible.builtin.template', 'homeassistant.kube.j2') }}"
      mariadb:
        name: "{{ db_name | default() }}"
        networks:
          - name: "{{ db_name }}"
            internal: true
        user: "{{ db_user }}"
        password: "{{ db_password }}"
        root_password: "{{ db_root_password }}"
        image_tag: "{{ homeassistant_db_image_tag | mandatory }}"

- name: Podman service deployment
  ansible.builtin.include_role:
    name: podman_service_deploy
