---
# tasks file for maxxberg.homeassistant
- name: Set project name
  set_fact:
    project_name: homeassistant
- name: Docker - Create volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - homea_config

- name: Create docker networks - web_backend
  docker_network:
    name: web_backend
    internal: yes
    state: present
- name: Create docker networks - ha_net
  docker_network:
    name: ha_net
    internal: yes
    state: present
    ipam_config:
    - subnet: "{{ ha_net_network }}"

- name: Create project directotory
  file:
    path: docker-compose/{{project_name}}
    state: directory
- name: Create config directory
  file: 
    path: docker-compose/{{project_name}}/config
    state: directory
- name: Create data directory
  file:
    path: docker-compose/{{project_name}}/data
    state: directory
#- name: Upload init files
#  copy:
#    src: init/
#    dest: docker-compose/{{project_name}}/init

- name: Test if old configuration exists
  ansible.builtin.stat:
    path: docker-compose/{{project_name}}/config/configuration.yaml
  register: config_exists

- name: Read old configuration
  ansible.builtin.slurp:
    src: docker-compose/{{project_name}}/config/configuration.yaml
  register: config
  when: config_exists.stat.exists

- name: debug
  debug:
    msg: "{{ (config.content | b64decode | replace(': !', ': ') | from_yaml) }}"

- name: Parse token and org
  set_fact:
    influx_token: "{{ (config.content | b64decode | replace(': !', ': ') | from_yaml).influxdb.token }}"
    influx_org: "{{ (config.content | b64decode | replace(': !', ': ') | from_yaml).influxdb.organization  }}"

- name: Render Home Assistant configuration
  template:
    src: configuration.yaml
    dest: docker-compose/{{project_name}}/config/
    force: yes
  when: not config_exists.stat.exists

- name: Create docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: docker-compose/{{project_name}}/docker-compose.yaml
    force: yes

- name: Docker - {{project_name}}
  docker_compose:
    project_src: docker-compose/{{project_name}}/
    state: present
    pull: yes