- name: Save configuration
  ansible.builtin.set_fact:
    podman_service_deploy_config_save: "{{ podman_service_deploy_config }}"

- name: Set mariadb_network (Needed because of lazy evaluation)
  ansible.builtin.set_fact:
    db_networks: "{{ podman_service_deploy_config.mariadb.networks }}"

- name: Include Mariadb
  ansible.builtin.include_role:
    name: .mariadb
  vars:
    mariadb_name: "{{ podman_service_deploy_config.mariadb.name }}"
    mariadb_dbname: "{{ podman_service_deploy_config.mariadb.dbname }}"
    mariadb_networks: "{{ db_networks }}"
    mariadb_user: "{{ podman_service_deploy_config.mariadb.user }}"
    mariadb_password: "{{ podman_service_deploy_config.mariadb.password }}"
    mariadb_root_password: "{{ podman_service_deploy_config.mariadb.root_password }}"
    mariadb_image_tag: "{{ podman_service_deploy_config.mariadb.image_tag | mandatory }}"
    mariadb_args: "{{ podman_service_deploy_config.mariadb.args | default() }}"

- name: Restore configuration
  ansible.builtin.set_fact:
    podman_service_deploy_config: "{{ podman_service_deploy_config_save }}"