- name: Set postgresql_network (Needed because of lazy evaluation)
  ansible.builtin.set_fact:
    db_networks: "{{ podman_service_deploy_config.postgresql.networks }}"
  when: podman_service_deploy_config.postgresql is defined

- name: Include Postgresql
  ansible.builtin.include_role:
    name: postgresql
  vars:
    postgresql_name: "{{ podman_service_deploy_configpostgresql.name }}"
    postgresql_dbname: "{{ podman_service_deploy_config.postgresql.dbname }}"
    postgresql_networks: "{{ db_networks }}"
    postgresql_user: "{{ podman_service_deploy_config.postgresql.user }}"
    postgresql_password: "{{ podman_service_deploy_config.postgresql.password }}"
    postgresql_image_tag: "{{ podman_service_deploy_config.postgresql.image_tag | mandatory }}"
    postgresql_args: "{{ podman_service_deploy_config.postgresql.args | default() }}"
  when: podman_service_deploy_config.postgresql is defined
