- name: Save configuration
  ansible.builtin.set_fact:
    podman_service_deploy_config_save: "{{ podman_service_deploy_config }}"

- name: Set redis_network (Needed because of lazy evaluation)
  ansible.builtin.set_fact:
    db_networks: "{{ podman_service_deploy_config.redis.networks }}"

- name: Include Redis
  ansible.builtin.include_role:
    name: redis
  vars:
    redis_name: "{{ podman_service_deploy_config.redis.name }}"
    redis_networks: "{{ db_networks }}"
    redis_args: "{{ podman_service_deploy_config.redis.args | default() }}"

- name: Restore configuration
  ansible.builtin.set_fact:
    podman_service_deploy_config: "{{ podman_service_deploy_config_save }}"